### ISSUE TITLE
Error trying to get contacts in getContacts() method: Class “\Brevo”\Model“\AllOfgetContactsContactsItems” not found.

### ISSUE THREAD

**Issue by soporte-innocard** [getbrevo/brevo-php#72]
Dear Brevo Team,
I have never had problems with ContactsAPI, but since 3 days ago when I try to call the getContacts() method, I get the following error:

`Class "\Brevo\Client\Model\AllOfgetContactsContactsItems" not found.`

From the error trace, this occurs when trying to deserialize the object "getContacts().
I want to know if this is an SDK issue and if there is currently a patch for this.

The version of Brevo I am currently using in composer is 2.0.7.

Edited: 
Bug fixed by downgrading version.
Failed version: 2.0.7
Correct version: 2.0.4 and earlier

**Comment by lukaspluemper** [comment]
That explains, why the problem still exists in v2.0.9.

**Comment by sowmyahora2001** [comment]
Fixed in https://github.com/getbrevo/brevo-php/releases/tag/v2.0.10

**Comment by dunebaud** [comment]
The error is still there in 2.0.10 and 2.0.13 I had to downgrade to 2.0.4 to make it work.
Issue should be reopened
